"""Provision runtime workspace files from Agent config and user-authored templates."""

from __future__ import annotations

import json
import secrets
import threading
import time
from dataclasses import dataclass, field
from importlib.resources import files as pkg_files
from pathlib import Path
from typing import Any

from PhyAgentOS.config.schema import Config
from PhyAgentOS.runtime.schemas.common import utc_now
from PhyAgentOS.runtime.state_io.atomic_file import atomic_write_text
from PhyAgentOS.runtime.state_io.markdown_yaml import read_yaml_block, write_yaml_block
from PhyAgentOS.runtime.watchdog.supervisor import WatchdogSupervisor

RUNTIME_TEMPLATE_NAMES = ("TARGETS.md", "SKILLRUNTIME.md")
RUNTIME_CONFIG_TEMPLATE_NAMES = (
    "configs/runtime/contracts/dummy_sim.runtime.yaml",
    "configs/runtime/contracts/libero_real.runtime.yaml",
    "configs/runtime/contracts/isaacsim_pipergo2.runtime.yaml",
    "configs/runtime/contracts/go2_builtin.runtime.yaml",
    "configs/runtime/sensors/dummy_sim.sensors.yaml",
)
_RUNTIME_INSTRUCTIONS = """# Runtime Protocol

This file is generated by PhyAgentOS for the Agent. It describes how to queue
runtime sessions. Do not use this file as runtime state.

## Runtime Files

- `TARGETS.md`: user-maintained target registry.
- `SKILLRUNTIME.md`: available runtime skill runtimes.
- `SESSIONS.md`: runtime session queue; the watchdog claims `pending` sessions.
- `ENVIRONMENT.md`: runtime environment state. It is created empty, then the
  runtime manager writes a target registry snapshot. Scene/object state is
  updated only by runtime/perception writers.

## Creating A Session

When the user asks to execute an enabled runtime target, append one item to the
`sessions` list in `SESSIONS.md`. Keep existing sessions and results intact.

Required shape:

```yaml
version: runtime_sessions_v1
sessions:
  - session_id: unique_short_id
    goal_id: optional_goal_id
    target_ref: target://target_id_from_TARGETS
    skillruntime_ref: skillruntime://skillruntime_id_from_SKILLRUNTIME
    task_description: user-facing task description
    verification_profile: strict
    status: pending
    priority: normal
    timeouts:
      queue_timeout_s: 30
      preflight_timeout_s: 20
      execute_timeout_s: 300
      policy_timeout_s: 10
    retry:
      max_retries: 0
      attempted: 0
    routing:
      target_endpoint: targetws://target-host:9002
      policy_endpoint: openpi://policy-host:8000
      adapter_resolution: strict_auto
      adapter_overrides: null
    execution:
      max_steps: 200
      replan_every_steps: 5
      action_chunk_mode: chunk_buffer
      chunk_switch_mode: hard_switch
      reset_policy: session_runner
      steps: null
    runtime_hints:
      perception_queries: []
      force_environment_refresh: false
      preferred_replan_every_steps: 5
    safety_profile:
      profile: default_simulation
      workspace_bounds: default
      stop_on_policy_timeout: true
    result: {}
```

Rules:

- Read `TARGETS.md` and `SKILLRUNTIME.md` before creating a session. Read
  `ENVIRONMENT.md` for the latest target runtime snapshot.
- Use only targets whose `TARGETS.md` entry has `enabled: true`.
- `target_ref` must match an id in `TARGETS.md`; `skillruntime_ref` must be listed in
  that target's `supported_skillruntimes`.
- Use endpoint values declared in `TARGETS.md` unless the user explicitly
  provides a different endpoint.
- For benchmark work, match `TARGETS.md benchmark_capabilities` against the
  structured `SKILLRUNTIME.md benchmark` declaration before writing a Session.
  Record `benchmark.execution_mode` explicitly; never infer it from
  `runtime_kind`.
- A `policy_loop` benchmark uses one root Session per episode and
  `execution.reset_policy: session_runner`. A `target_native` benchmark uses
  one root Session per suite, a benchmark-specific BuiltinSkillRuntime, and
  `execution.reset_policy: skillruntime_managed`.
- Set the Session-level `verification_profile` to `strict`, `audit`, or
  `recovery`. Verification provider, endpoint, timeout, retention, and budget
  are global Agent configuration and must not be copied into the Session.
- Never call `target.benchmark.*` directly. Target-native access belongs to the
  selected BuiltinSkillRuntime through `TargetSessionHandle`.
- Builtin command runtimes such as `go2_builtin_command` must include
  structured `execution.steps`; do not rely on `task_description` for the
  executable command. For Go2, use commands exposed by the target, for example:

```yaml
execution:
  max_steps: 1
  replan_every_steps: 1
  action_chunk_mode: chunk_buffer
  chunk_switch_mode: hard_switch
  steps:
    - command: stand_up
```

For Go2 movement, prefer an explicit posture sequence and put velocity fields
under `params`:

```yaml
execution:
  max_steps: 3
  replan_every_steps: 1
  action_chunk_mode: chunk_buffer
  chunk_switch_mode: hard_switch
  steps:
    - command: stand_up
    - command: balance_stand
    - command: move
      params:
        vx: 0.5
        vy: 0.0
        vyaw: 0.0
        duration_s: 1.0
```

- Do not manually edit `ENVIRONMENT.md`; it is runtime state managed by
  PhyAgentOS.
"""


@dataclass
class RuntimeWorkspaceReport:
    workspace: Path
    created: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)
    updated: list[str] = field(default_factory=list)
    disabled_targets: list[str] = field(default_factory=list)
    enabled_targets: list[str] = field(default_factory=list)
    watchdog_started: bool = False


class RuntimeWorkspaceManager:
    """Create runtime workspace files and optionally supervise sessions."""

    def __init__(self, config: Config):
        self.config = config
        self.workspace = config.runtime_workspace_path
        self.environment_workspace = config.workspace_path
        self._watchdog: BackgroundWatchdog | None = None
        self._verification_token = secrets.token_urlsafe(32)

    def provision(self) -> RuntimeWorkspaceReport:
        report = RuntimeWorkspaceReport(workspace=self.workspace)
        if not self.config.runtime.enabled:
            return report
        self.workspace.mkdir(parents=True, exist_ok=True)
        templates = pkg_files("PhyAgentOS") / "templates"
        self._copy_missing_templates(templates, report)
        self.write_runtime_instructions(report)
        self._ensure_empty_sessions(report)
        self._ensure_empty_environment(report)
        self._apply_target_enabled_overrides(report)
        self.write_environment_targets_snapshot(report)
        return report

    def start_watchdog(self) -> RuntimeWorkspaceReport:
        report = self.provision()
        if not self.config.runtime.enabled or not self.config.runtime.autostart_watchdog:
            return report
        if self._watchdog is None:
            self._watchdog = BackgroundWatchdog(
                self.workspace,
                environment_workspace=self.environment_workspace,
                poll_interval_s=self.config.runtime.watchdog_poll_interval_s,
                verification_enabled=self.config.agents.verification.service_enabled,
                verification_settings={
                    "local_service_url": f"http://{'127.0.0.1' if self.config.agents.verification.service_host == '0.0.0.0' else self.config.agents.verification.service_host}:{self.config.agents.verification.service_port}",
                    "remote_target_url": self.config.agents.verification.remote_target_url,
                    "max_replans_per_episode": self.config.agents.verification.max_replans_per_episode,
                    "max_verifier_calls_per_run": self.config.agents.verification.max_verifier_calls_per_run,
                    "timeout_s": self.config.agents.verification.timeout_s,
                    "episode_token": self._verification_token,
                },
            )
            self._watchdog.start()
            report.watchdog_started = True
        return report

    def stop_watchdog(self) -> None:
        if self._watchdog is None:
            return
        self._watchdog.stop()
        self._watchdog = None

    @property
    def verification_token(self) -> str:
        return self._verification_token

    def _copy_missing_templates(self, templates: Any, report: RuntimeWorkspaceReport) -> None:
        for name in RUNTIME_TEMPLATE_NAMES:
            src = templates / name
            dest = self.workspace / name
            if dest.exists():
                report.skipped.append(name)
                continue
            dest.write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
            report.created.append(name)
        for name in RUNTIME_CONFIG_TEMPLATE_NAMES:
            src = templates.joinpath(*Path(name).parts)
            dest = self.workspace / name
            if dest.exists():
                report.skipped.append(name)
                continue
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
            report.created.append(name)

    def _ensure_empty_sessions(self, report: RuntimeWorkspaceReport) -> None:
        sessions_path = self.workspace / "SESSIONS.md"
        if sessions_path.exists():
            report.skipped.append("SESSIONS.md")
            return
        write_yaml_block(
            sessions_path,
            "Runtime Sessions",
            {"version": "runtime_sessions_v1", "sessions": []},
        )
        report.created.append("SESSIONS.md")

    def _ensure_empty_environment(self, report: RuntimeWorkspaceReport) -> None:
        created = False
        skipped = False
        for environment_path in self._environment_paths():
            environment_path.parent.mkdir(parents=True, exist_ok=True)
            if environment_path.exists():
                skipped = True
                continue
            environment_path.write_text("", encoding="utf-8")
            created = True
        if created:
            report.created.append("ENVIRONMENT.md")
        elif skipped:
            report.skipped.append("ENVIRONMENT.md")

    def write_runtime_instructions(self, report: RuntimeWorkspaceReport | None = None) -> RuntimeWorkspaceReport:
        report = report or RuntimeWorkspaceReport(workspace=self.workspace)
        path = self.workspace / "RUNTIME.md"
        existed = path.exists()
        path.write_text(_RUNTIME_INSTRUCTIONS, encoding="utf-8")
        (report.updated if existed else report.created).append("RUNTIME.md")
        return report

    def _apply_target_enabled_overrides(self, report: RuntimeWorkspaceReport) -> None:
        overrides = dict(self.config.runtime.target_enabled)
        if not overrides:
            return
        targets_path = self.workspace / "TARGETS.md"
        if not targets_path.exists():
            return
        document = read_yaml_block(targets_path)
        targets = document.get("targets")
        if not isinstance(targets, list):
            return
        changed = False
        for target in targets:
            if not isinstance(target, dict):
                continue
            target_id = target.get("id")
            if not isinstance(target_id, str) or target_id not in overrides:
                continue
            enabled = bool(overrides[target_id])
            if target.get("enabled") != enabled:
                target["enabled"] = enabled
                changed = True
            if enabled:
                report.enabled_targets.append(target_id)
            else:
                report.disabled_targets.append(target_id)
        if changed:
            write_yaml_block(targets_path, "Runtime Targets", document)
            report.updated.append("TARGETS.md")

    def write_environment_targets_snapshot(
        self,
        report: RuntimeWorkspaceReport | None = None,
    ) -> RuntimeWorkspaceReport:
        report = report or RuntimeWorkspaceReport(workspace=self.workspace)
        existing_source = self._latest_existing_environment()
        if existing_source is not None:
            created, updated = self._mirror_environment_from(existing_source)
            if created and "ENVIRONMENT.md" not in report.created:
                report.created.append("ENVIRONMENT.md")
            elif updated and "ENVIRONMENT.md" not in report.created and "ENVIRONMENT.md" not in report.updated:
                report.updated.append("ENVIRONMENT.md")
            return report

        targets_path = self.workspace / "TARGETS.md"
        if not targets_path.exists():
            return report
        try:
            document = read_yaml_block(targets_path)
        except Exception:
            return report
        targets = document.get("targets")
        if not isinstance(targets, list):
            return report

        now = utc_now().isoformat()
        payload = {
            "schema_version": "PhyAgentOS.environment.v2",
            "updated_at": now,
            "targets": {
                str(target["id"]): self._target_snapshot(target, now)
                for target in targets
                if isinstance(target, dict) and isinstance(target.get("id"), str)
            },
        }
        text = (
            "# Environment State\n\n"
            "Auto-updated by PhyAgentOS runtime workspace manager.\n\n"
            f"```json\n{json.dumps(payload, indent=2, ensure_ascii=False)}\n```\n"
        )
        existed = all(path.exists() for path in self._environment_paths())
        for env_path in self._environment_paths():
            env_path.parent.mkdir(parents=True, exist_ok=True)
            atomic_write_text(env_path, text)
        if "ENVIRONMENT.md" not in report.created and "ENVIRONMENT.md" not in report.updated:
            (report.updated if existed else report.created).append("ENVIRONMENT.md")
        return report

    def _environment_paths(self) -> tuple[Path, ...]:
        """Runtime-local and agent-visible environment files."""
        runtime_path = self.workspace / "ENVIRONMENT.md"
        agent_path = self.environment_workspace / "ENVIRONMENT.md"
        if runtime_path == agent_path:
            return (runtime_path,)
        return (runtime_path, agent_path)

    def _latest_existing_environment(self) -> Path | None:
        candidates = [
            path
            for path in self._environment_paths()
            if path.exists() and path.stat().st_size > 0
        ]
        if not candidates:
            return None
        return max(candidates, key=lambda path: path.stat().st_mtime_ns)

    def _mirror_environment_from(self, source: Path) -> tuple[bool, bool]:
        """Mirror the newest non-empty environment without overwriting it."""
        content = source.read_text(encoding="utf-8")
        created = False
        updated = False
        for dest in self._environment_paths():
            if dest == source:
                continue
            dest.parent.mkdir(parents=True, exist_ok=True)
            if not dest.exists():
                atomic_write_text(dest, content)
                created = True
                continue
            if dest.read_text(encoding="utf-8") != content:
                atomic_write_text(dest, content)
                updated = True
        return created, updated

    def _target_snapshot(self, target: dict[str, Any], now: str) -> dict[str, Any]:
        runtime = target.get("runtime") if isinstance(target.get("runtime"), dict) else {}
        config = target.get("config") if isinstance(target.get("config"), dict) else {}
        enabled = bool(target.get("enabled", True))
        endpoint = runtime.get("target_endpoint")
        return {
            "target_id": target.get("id"),
            "enabled": enabled,
            "target_class": target.get("target_class"),
            "target_kind": target.get("target_kind"),
            "workspace": target.get("workspace"),
            "supported_skillruntimes": list(target.get("supported_skillruntimes") or []),
            "connection_state": {
                "status": "disabled" if not enabled else ("configured" if endpoint else "unconfigured"),
                "endpoint": endpoint,
                "checked_at": now,
                "source": "TARGETS.md",
            },
            "runtime": {
                "target_runtime": runtime.get("target_runtime"),
                "target_adapter": runtime.get("target_adapter"),
                "runtime_contract_ref": str(runtime.get("runtime_contract_ref") or ""),
            },
            "benchmark": {
                key: config[key]
                for key in ("benchmark_name", "task_id", "init_state_id")
                if key in config
            },
        }


class BackgroundWatchdog:
    """Run WatchdogSupervisor in a daemon thread owned by the Agent process."""

    def __init__(
        self,
        workspace: Path,
        *,
        environment_workspace: Path,
        poll_interval_s: float,
        verification_enabled: bool,
        verification_settings: dict[str, Any],
    ):
        self.workspace = workspace
        self.environment_workspace = environment_workspace
        self.poll_interval_s = max(0.05, float(poll_interval_s))
        self.verification_enabled = verification_enabled
        self.verification_settings = dict(verification_settings)
        self._stop = threading.Event()
        self._thread = threading.Thread(target=self._run, name="phyagentos-runtime-watchdog", daemon=True)

    def start(self) -> None:
        self._thread.start()

    def stop(self) -> None:
        self._stop.set()
        self._thread.join(timeout=2.0)

    def _run(self) -> None:
        supervisor = WatchdogSupervisor(
            self.workspace,
            environment_workspace=self.environment_workspace,
            verification_enabled=self.verification_enabled,
            verification_settings=self.verification_settings,
        )
        while not self._stop.is_set():
            try:
                ran = supervisor.run_once()
                if ran:
                    self._mirror_environment_to_runtime_workspace()
            except Exception:
                ran = False
            if not ran:
                self._stop.wait(self.poll_interval_s)

    def _mirror_environment_to_runtime_workspace(self) -> None:
        src = self.environment_workspace / "ENVIRONMENT.md"
        dest = self.workspace / "ENVIRONMENT.md"
        if src == dest or not src.exists():
            return
        try:
            atomic_write_text(dest, src.read_text(encoding="utf-8"))
        except Exception:
            return
